### ISSUE TITLE
jQuery event when reordering is made

### ISSUE THREAD

**Issue by kokolem** [alsoicode/django-admin-sortable#193]
I think it would be great if django-admin-sortable would do a jQuery event when reordering is made, like Django when new inline is added or removed.
Possible syntax:
`$(document).on('reordering', function() {
       //reordering is made
    });`

**Comment by alsoicode** [comment]
Pull requests are always welcome.

**Comment by kokolem** [comment]
As I have no clue how your code works, could you just add this line to the point when a user changes the order, please?
`$(document).trigger('order:changed');`

**Comment by alsoicode** [comment]
No offense, but the best way to learn is to try. I'll see if I can find some time today.

**Comment by kokolem** [comment]
I tried, but because of the lack of coments in your code, I have absolutly no clue how it works. But anyway, thank you so much for creating this awsome project! It helped me a lot, and with jQuery event after reordering it will help me even more. Thanks!

**Comment by alsoicode** [comment]
Let me see if I can add a way for you to add additional JavaScript to be executed after the ajax call is made to perform the ordering.

**Comment by kokolem** [comment]
Thank you! Is there any way I can help?

**Comment by alsoicode** [comment]
The approach I'm currently taking is to create a custom template that extends the adminsortable/change_list.html template in order to add a JavaScript callback function to be executed in the success callback of the ajax function.

Adminsortable is pretty flexible when it comes to templating, and if I can get it working, would provide a way for you (and others) to add the custom callback without having to hard code the event.

**Comment by alsoicode** [comment]
Ok, I have a solution working for the base sorting functionality. I need to also address this for inline templates. In a nutshell, you'll need to create a custom template that extends the `adminsortable/change_list.html` template or one of the inline model templates.

In this template, you can define your event listener and also the callback to be executed on sort success. Here's an example:

```
# custom_change_list.html
{% extends 'adminsortable/change_list.html' %}

{% block extrahead %}
  {{ block.super }}

  <script>
    django.jQuery(document).on('order:changed', function(event) {
      console.log(event.message);
    });

    window['afterSortCallback'] = function() {
      django.jQuery(document).trigger({
        type: 'order:changed',
        message: 'Order changed',
        time: new Date()
      });
    };
  </script>
{% endblock %}
```

Your sortable admin class needs to use this template instead of the default as such:

```
class YourModelAdmin(SortableAdmin):
    sortable_change_list_template = 'adminsortable/custom_change_list.html'
```

Once my changes are in, the admin sortable JavaScript will check for the existence of the callback function on the window, and if present execute the function. Do you think this will work for your use case?

**Comment by kokolem** [comment]
I am using the inline sorting, so this is not working. Is there any way to make it work with inlines too?

**Comment by alsoicode** [comment]
Yes - 

> Ok, I have a solution working for the base sorting functionality. I need to also address this for inline templates. 

The same workflow will apply for inlines. Do you feel the example above will give you the functionality you're needing?

**Comment by kokolem** [comment]
Yes, absolutly!

**Comment by alsoicode** [comment]
Ok, let me get the same functionality in place on the inline templates and get the documentation updated. I will hopefully be able to release the changes today or tomorrow. I'm slammed on a big refactor on a separate project at the moment.

**Comment by kokolem** [comment]
Take your time, I'll be glad if you make it soon, but it doesn't hurry

**Comment by alsoicode** [comment]
Hi @kokolem. I've been able to add the custom callback for inlines, however, there's a side-effect that you should be aware of, and I don't think there's a way around this, due to the nature of inline models, but I can continue to investigate.

Currently, an event will be emitted for every inline instance. If there are 3 inlines, you'll see 3 events. If there are 23, you'll see 23 events once sorting has been completed.

**Comment by alsoicode** [comment]
Actually, nevermind - I got it figured out :) I should be able to get this code merged and released to you today.

**Comment by kokolem** [comment]
Thank you!

**Comment by alsoicode** [comment]
Ok, here you go: https://github.com/alsoicode/django-admin-sortable#custom-js-callbacks-after-sorting-is-complete

I have released 2.1.6 to PyPi. Please let me know if you have any questions.

**Comment by alsoicode** [comment]
@kokolem Can you confirm the 2.1.6 release is working as expected for you?

**Comment by kokolem** [comment]
Hi. I will have a look at it today.

**Comment by alsoicode** [comment]
If you're not able to extend `adminsortable/change_form.html`, something is probably wrong with the `TEMPLATES` setting.

You also need to change the name of the variable that is provided by the `SortableAdmin` class. Instead of `after_sorting`, use `after_sorting_js_callback_name` and make sure you set that on your admin class. The value of that variable is really irrelevant. It just needs to be a string.

**Comment by kokolem** [comment]
Do you see that last line in the templates Django tried? It says skipped. I tried to open that file in explorer - and voila! That is the template I need to extend. But Django skips it. That doesn't make sense.

**Comment by iambrandontaylor** [comment]
Take a look in the source code at the "sample project" directory. You'll
see a working example based on the ProjectAdmin, complete with template
overrides and settings.

**Comment by alsoicode** [comment]
Any luck?

**Comment by kokolem** [comment]
Nope. This makes no sence. Maybe I can just copy
adminsortable/change_form.html and hard code my stuff into it and then set
in admin.py?

**Comment by alsoicode** [comment]
Clone this repo and run the sample project. Make sure your settings for templates match what's in the sample project. Is the problem that you're still not able to extend the `adminsortable/change_form.html` template?

**Comment by kokolem** [comment]
Yes. As you saw in the screenshot, Django skips it for unknown reason.

**Comment by alsoicode** [comment]
What is your `TEMPLATES` setting?

**Comment by kokolem** [comment]
Sorry, I'm not gonna get to my PC until monday. But then I am gonna have a
look at it ASAP.

**Comment by alsoicode** [comment]
Closing for now. If you're still having issues, please invite me to your repo so I can see the specific implementation.
