### ISSUE TITLE
SortableMixin conflicts with django-modeltranslation

### ISSUE THREAD

**Issue by ton77v** [alsoicode/django-admin-sortable#213]
Hello! There is a problem if you trying to use SortableMixin for a model, that's registered with django-modeltranslation

To reproduce:
install django-modeltranslation

models.py:
```
class Some2(models.Model):
    from django.utils import timezone
    test = models.CharField(max_length=1)
    test2 = models.CharField(max_length=222, primary_key=True)

class SortaBug8(Some2, SortableMixin):
    tag_order = models.PositiveIntegerField(default=0, editable=False, db_index=True)

    class Meta:
        ordering = ['tag_order', ]
```

admin.py:
```
@admin.register(SortaBug8)
class CategoryTrAdmin(SortableAdmin):
    pass
```

translation.py:
```
@register(Some2)
class SomeTranslationOptions(TranslationOptions):
    fields = ('test',)


@register(SortaBug8)
class SortaBugTranslationOptions(TranslationOptions):
    pass
```

When you are adding a new entry, an error will be raised
a call to `self.order_field_name` raises it, since there is no such an attribute

**Comment by alsoicode** [comment]
Do you have a sample project with all of the necessary configuration you could zip up and send to me?

**Comment by ton77v** [comment]
Sure, thanks
I've created a test project & app and uploaded to github, this is an app:
https://github.com/ton77v/test8/tree/master/testapp

If you try adding a SortTest object, an error appears

**Comment by alsoicode** [comment]
Thanks, I'll take a look as soon as I can.

**Comment by alsoicode** [comment]
@ton77v Sorry to take so long to get back to you. The problem seems to be that when your admin class inherits from both SortableAdmin and TranslationAdmin, that the SortableMIxin's __init__() is either being skipped entirely or is firing too late.

This runs the routine that sets the `order_field_name property`, which looks in the model's Meta class for what field you've specified for ordering to happen on to be used to calculate the next order when adding.

Perhaps Django's `admin.register()` method isn't designed to accommodate more than one class, and that's why it's happening. I've tried switching the order of the classes, manually executing the init in a super(), but unfortunately that's not working.

Bypassing that one field in the save is relatively easy, but I can't guarantee that fixing that one issue isn't going to lead to more problems for you working in tandem with the modeltranslation package.

**Comment by ton77v** [comment]
Thanks, Brandon. I created some ugly hack to skip the problems, it's a pity that there is no good way out, but I can live with that. )) I think you are right about admin.register() and will try not to mix few classes next time.
